### ISSUE TITLE
Support Dockerfile as deployable

### ISSUE THREAD

**Issue by jdewinne** [xebialabs-community/xld-openshift-plugin#10]
Allow a dockerfile to be uploaded and used as deployable.

**Comment by vpartington** [comment]
A Dockerfile? Are you sure? Wouldn't you rather have a Docker image as a deployable?

Rebuilding the Docker image on every deploy doesn't seem the most efficient or repeatable process.

Or is this a OpenShift thing?

**Comment by MarkRx** [comment]
That does seem strange. I would think you would want to use a docker image instead.

**Comment by jdewinne** [comment]
Why would this be so strange? This is about also letting OpenShift do the build part.
[Dockerfile source](https://docs.openshift.com/enterprise/3.0/dev_guide/builds.html#dockerfile-source)

**Comment by vpartington** [comment]
Aha, so this _is_ an OpenShift thing. :-) OK.

**Comment by alephnot0** [comment]
Using a Dockerfile is almost equivalent to using a docker image as a Dockerfile defines the image.  I say almost as there is a possibility that the image could have changed between deployments so you would have to be careful.  It is faster than using a docker image as the Dockerfile might be 2KB rather than a 1GB image.

**Comment by MarkRx** [comment]
Ah the build mechanism. I thought you were referring to doing pushes to the internal openshift docker registry.

**Comment by jdewinne** [comment]
See v6.5.0
